import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import type { ReactNode } from "react";
import { ZodErrorProvider } from "@/providers/zodProvider";
import { NextAuthProvider } from "@/providers/nextAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <NextAuthProvider>
            <ZodErrorProvider />
            {children}
          </NextAuthProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
};
